version: "3.8"

services:
  redis:
    image: redis:latest
    restart: unless-stopped

  communication-control:
    image: ${REGISTRY}/hive-com-control:${TAG}
    ports:
      - "${COM_PORT}:8080"
    depends_on:
      - redis
    environment:
      - Redis__ConnectionString=redis:6379
    restart: unless-stopped

  map-client:
    image: ${REGISTRY}/hive-map-client:${TAG}
    ports:
      - "${MAP_PORT}:80"
    depends_on:
      - communication-control
    restart: unless-stopped

  hive-mind:
    image: ${REGISTRY}/hive-mind:${TAG}
    ports:
      - "${HIVE_PORT}:5149"
    depends_on:
      - redis
      - communication-control
    environment:
      - Redis__ConnectionString=redis:6379
      - CommunicationConfiguration__CommunicationControlIP=communication-control
      - CommunicationConfiguration__HiveIP=hive-mind
      - CommunicationConfiguration__CommunicationControlPort=8080
      - CommunicationConfiguration__HivePort=5149
    restart: unless-stopped
